### ISSUE TITLE
investigate ability to configure a proxy endpoint for gRPC channel

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-php#42]

**Comment by onethumb** [comment]
I'm probably the instigator of this Issue as well, via text message, so I'll just elaborate for future curious people. :)

On high-throughput, low-latency services like `Momento`, we often use a proxy (L4 and/or L7) to maintain a pool of connections to reduce latency due to handshaking in the network layers (TCP, TLS, etc) so we can re-use keepalive connections that have already handled all the negotiations the vast majority of the time.

Low-level libraries like `libcurl` and higher level libraries like `guzzle` and `aws-php-sdk` already provide easy ways to do these sorts of injections, which can have a massive reduction in latency.

Thanks!

**Comment by onethumb** [comment]
One reason this is more important for PHP than some other languages is that PHP resets state on every HTTP request. It's one of its superpowers, but also one of its downsides. It's a double-edge sword. Using a proxy helps it be a single-edged sword instead. :)

**Comment by cprice404** [comment]
@onethumb we were evaluating our options for dealing with the state reset just yesterday, so this request is timely, thank you.

In your scenario are you running the proxy on localhost then, I presume?

**Comment by onethumb** [comment]
Yeah, typically we run a proxy on localhost or in a sidecar or similar. Sometimes it's something generic, like `haproxy`, but other times it's something specific like `twemproxy` or `McRouter` or whatever. (We like `haproxy` best).

**Comment by cprice404** [comment]
Thanks for the info @onethumb .  This is on our short list to dig into.

**Comment by cprice404** [comment]
one more quick question @onethumb - do you have any general preference for running `haproxy` as L4 vs L7?  Obviously it's a case-by-case thing, but any general thoughts?

**Comment by onethumb** [comment]
When it's a service which speaks HTTPS, we prefer using it at L7 so it can keepalive all the TLS handshaking and such as well as the TCP state. If it's not (memcached, say), we use L4.

**Comment by ksmotiv8** [comment]
This may be a silly question / digression - but do you plan to run this on lambda as well? Would this be an extension?

**Comment by onethumb** [comment]
Yes, we have cases where we use this on Lambda, since some of our Lambda implementations still reset PHP state between requests. (Not all of them do).

One interesting option is for you to provide a built-in proxy via your client, similar to what `memcached` has recently done: https://github.com/memcached/memcached/wiki/Proxy

Then your customers, of _any_ language, have an optional proxy that's well-tested and purpose-built to deliver value.

**Comment by ksmotiv8** [comment]
What if… we had a proxy that speaks memcached protocol (or resp) that you can connect to with your existing memcached libraries, and it just tackles the Momento specific grpc magic for you? You can run this alongside your server for now. Soon, it’ll speak Momento grpc protocol as well. An additional caveat to keep in mind: it only supports gets and sets atm. pelikan/src/proxy/momento/src/protocol at momento-redis · brayniac/pelikangithub.comOn Oct 29, 2022, at 8:36 AM, Don MacAskill ***@***.***> wrote:﻿
Yes, we have cases where we use this on Lambda, since some of our Lambda implementations still reset PHP state between requests. (Not all of them do).
One interesting option is for you to provide a built-in proxy via your client, similar to what memcached has recently done: https://github.com/memcached/memcached/wiki/Proxy
Then your customers, of any language, have an optional proxy that's well-tested and purpose-built to deliver value.

**Comment by onethumb** [comment]
It's been at least a year since we last played with Pelikan, but in theory, I love this approach. In practice? Time will tell. We need `add` and `getMultiple` pretty badly, `increment` and `decrement` are also important but less mission-critical.

**Comment by ksmotiv8** [comment]
To be clear, this isn’t Pelikan cache per se. this is a - lightweight - memcache protocol compatible proxy that you can run as a sidecar, and it takes to Momento on your behalf over grpc. It minimizes the amount of code changes you need to get started, and I’m learning that it can have a utility for php stacks. We are working on add and getMultiple. Will add it to this proxy as well, if you think it can be useful. On Nov 2, 2022, at 5:34 PM, Don MacAskill ***@***.***> wrote:﻿
It's been at least a year since we last played with Pelikan, but in theory, I love this approach. In practice? Time will tell. We need add and getMultiple pretty badly, increment and decrement are also important but less mission-critical.

**Comment by pgautier404** [comment]
@onethumb We've added reverse proxying capability to the cache client in version 0.4.0 of the SDK. For more information, check out [the proxying README](https://github.com/momentohq/client-sdk-php/blob/main/README-proxying.md) which shows an example of using the client with `haproxy`. Thanks again for your feedback, and let us know what you think!
